# octave 2
42=KEY_GRAVE
43=KEY_1
44=KEY_2
45=KEY_3
46=KEY_4
47=KEY_5

# octave 3
48=KEY_6
49=KEY_7
50=KEY_8
51=KEY_9
52=KEY_0
53=KEY_MINUS
54=KEY_EQUAL
55=KEY_W
56=KEY_E
57=KEY_R
58=KEY_T
59=KEY_Y
60=KEY_U

# octave 4
61=KEY_I
62=KEY_O
63=KEY_P
64=KEY_LEFTBRACE
65=KEY_RIGHTBRACE
66=KEY_BACKSLASH
67=KEY_S
68=KEY_D
69=KEY_F
70=KEY_G
71=KEY_H

# octave 5
72=KEY_J
73=KEY_K
74=KEY_L
75=KEY_SEMICOLON
76=KEY_APOSTROPHE
77=KEY_Z
78=KEY_X
